/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dam108t2_interfacesgraficas;

import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author JDoval
 */
public class dam108t2e511 extends javax.swing.JFrame {
    private _BuscaMinas juego;
    public int numeroBombas;
    private JButton tablero[][];
    /**
     * Creates new form dam108t2e511
     */
    public dam108t2e511() {
        initComponents();
        
        tablero = new JButton[8][8];
        for (int f = 0; f < tablero.length; f++) {
            for (int c = 0; c < tablero[f].length; c++) {
                tablero[f][c] = new JButton();
                tablero[f][c].setFont(new java.awt.Font("Tahoma", 0, 36));
                tablero[f][c].addActionListener(new java.awt.event.ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent evt) {
                        FActionPerformed(evt);
                    }
                });
                tablero[f][c].setName(Integer.toString(f)+ Integer.toString(c));
                tablero[f][c].setBackground(Color.white);
                tablero[f][c].setText("");
                PanelCasillas.add(tablero[f][c]);
            }
        }

    }

    public void FActionPerformed(ActionEvent e){
        String nn = ((JButton) e.getSource()).getName();
        int fila = Integer.parseInt(nn.substring(0, 1));
        int col = Integer.parseInt(nn.substring(1, 2));
        int x = juego.elegir(fila, col);
        if (x == -1) { //perdiste
            ((JButton) e.getSource()).setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Has perdido");
            System.exit(0);
        }
        else {
            for (int f = 0; f < 8; f++) {
                for (int c = 0; c < 8; c++) {
                    if(juego.casillas[f][c].descubierta){
                        tablero[f][c].setText(Integer.toString(juego.casillas[f][c].valor));
                        tablero[f][c].setBackground(Color.yellow);
                    }
                }
                if (juego.ganaste()){
                    JOptionPane.showMessageDialog(this, "Has ganado");
                    System.exit(0);
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelInferior = new javax.swing.JPanel();
        nBombas = new javax.swing.JButton();
        PanelCasillas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelInferior.setMinimumSize(new java.awt.Dimension(500, 100));
        PanelInferior.setPreferredSize(new java.awt.Dimension(500, 100));

        nBombas.setText("Numero de Bombas");
        nBombas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nBombasActionPerformed(evt);
            }
        });
        PanelInferior.add(nBombas);

        getContentPane().add(PanelInferior, java.awt.BorderLayout.PAGE_END);

        PanelCasillas.setMinimumSize(new java.awt.Dimension(500, 500));
        PanelCasillas.setPreferredSize(new java.awt.Dimension(500, 500));
        PanelCasillas.setLayout(new java.awt.GridLayout(8, 8));
        getContentPane().add(PanelCasillas, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nBombasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nBombasActionPerformed
        String nbS = JOptionPane.showInputDialog("Introduce el numero de bombas (maximo 20)");
        int nb = Integer.parseInt(nbS);
        numeroBombas = nb;
        juego = new _BuscaMinas (8,8,numeroBombas);
    }//GEN-LAST:event_nBombasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dam108t2e511.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dam108t2e511.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dam108t2e511.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dam108t2e511.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dam108t2e511().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCasillas;
    private javax.swing.JPanel PanelInferior;
    private javax.swing.JButton nBombas;
    // End of variables declaration//GEN-END:variables
}
