/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dam108t2_interfacesgraficas;

import java.time.LocalDateTime;
import java.time.LocalTime;
import static java.time.temporal.ChronoUnit.SECONDS;
import javax.swing.JOptionPane;

/**
 *
 * @author JDoval
 */
public class dam108t3e506 extends javax.swing.JFrame {

    /**
     * Creates new form dam108t3e506
     */
    public dam108t3e506() {
        initComponents();
        movil = new cMovilPrepago_v4(635294544, 1f, 0.15f, 0.10f, 100.0f);
        float saldo = movil.consultarSaldo();
        String txt = Float.toString(saldo);
        textSaldo.setText(txt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        llamar = new javax.swing.JButton();
        colgar = new javax.swing.JButton();
        labelSaldo = new javax.swing.JLabel();
        textSaldo = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        nMovil = new javax.swing.JMenuItem();
        eLlamada = new javax.swing.JMenuItem();
        cMLlamada = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teléfono prepago");

        llamar.setText("Llamar");
        llamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                llamarActionPerformed(evt);
            }
        });

        colgar.setText("Colgar");
        colgar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colgarActionPerformed(evt);
            }
        });

        labelSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSaldo.setText("Saldo:");

        jMenu1.setText("Config");

        nMovil.setText("Número de movil");
        nMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nMovilActionPerformed(evt);
            }
        });
        jMenu1.add(nMovil);

        eLlamada.setText("Establec. llamada");
        eLlamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eLlamadaActionPerformed(evt);
            }
        });
        jMenu1.add(eLlamada);

        cMLlamada.setText("Coste minuto llamada");
        cMLlamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cMLlamadaActionPerformed(evt);
            }
        });
        jMenu1.add(cMLlamada);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(labelSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(colgar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(llamar, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(llamar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colgar)
                .addGap(18, 18, 18)
                .addComponent(labelSaldo)
                .addGap(18, 18, 18)
                .addComponent(textSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void llamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_llamarActionPerformed
        float saldo = movil.consultarSaldo();
        if (saldo == 0 ) JOptionPane.showMessageDialog(this,"El saldo es 0 no se pueden efectuar llamadas");
        else {
            localDateTime = LocalDateTime.now();
            horaInicio = localDateTime.toLocalTime();

            llamar.setEnabled(false);
            colgar.setEnabled(true);
        }
    }//GEN-LAST:event_llamarActionPerformed

    private void colgarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colgarActionPerformed
        llamar.setEnabled(true);
        colgar.setEnabled(false);

        localDateTime = LocalDateTime.now();
        horaFin = localDateTime.toLocalTime();
        long segundosLlamada = Math.abs(SECONDS.between(horaFin, horaInicio));
        int segs = (int) segundosLlamada;

        movil.efectuarLlamada(segs);
        float saldo = movil.consultarSaldo();
        String txt = Float.toString(saldo);
        textSaldo.setText(txt);
    }//GEN-LAST:event_colgarActionPerformed

    private void nMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nMovilActionPerformed
        String nMovilCadena = JOptionPane.showInputDialog("Introduce un número del movil");
        long nMovil = Long.parseLong(nMovilCadena);
        movil.setNumeroMovil(nMovil);
        JOptionPane.showMessageDialog(this,"El número del movil es: "+movil.getNumeroMovil());
    }//GEN-LAST:event_nMovilActionPerformed

    private void eLlamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eLlamadaActionPerformed
        String eLlamadaCadena = JOptionPane.showInputDialog("Introduce el establecimiento de llamada.");
        float eLlamada = Float.parseFloat(eLlamadaCadena);
        movil.setCosteEstablecLlamada(eLlamada);
        JOptionPane.showMessageDialog(this,"El establecimiento de llamada es: "+movil.getCosteEstablecLlamada()+" €.");       
    }//GEN-LAST:event_eLlamadaActionPerformed

    private void cMLlamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cMLlamadaActionPerformed
        String cMLlamadaCadena = JOptionPane.showInputDialog("Introduce el coste del minuto.");
        float cMLlamada = Float.parseFloat(cMLlamadaCadena);
        movil.setCosteMinutoLlamada(cMLlamada);
        JOptionPane.showMessageDialog(this,"El coste del minuto de llamada es: "+movil.getCosteMinutoLlamada()+" €.");
    }//GEN-LAST:event_cMLlamadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dam108t3e506.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dam108t3e506.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dam108t3e506.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dam108t3e506.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dam108t3e506().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cMLlamada;
    private javax.swing.JButton colgar;
    private javax.swing.JMenuItem eLlamada;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JButton llamar;
    private javax.swing.JMenuItem nMovil;
    private javax.swing.JTextField textSaldo;
    // End of variables declaration//GEN-END:variables
    cMovilPrepago_v4 movil;
    LocalDateTime localDateTime;
    LocalTime horaInicio;
    LocalTime horaFin;
}
