/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dam108t2_interfacesgraficas;

import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author JDoval
 */
public class dam108t2e509 extends javax.swing.JFrame {

    /**
     * Creates new form dam108t2e509
     */
    public dam108t2e509() {
        initComponents();


        myTimer = new Timer(10, new java.awt.event.ActionListener () {
        public void actionPerformed(java.awt.event.ActionEvent e){
            int MIN_ALTURA = getHeight()-110;
            int MAX_ALTURA = 0;
            
            if (direccion) Bola.setLocation(Bola.getX(),Bola.getY() - 1); // hacia arriba
            else Bola.setLocation(Bola.getX(),Bola.getY() + 1);
            
            if (Bola.getY() == MAX_ALTURA) direccion = false;
            if (Bola.getY() == MIN_ALTURA )direccion = true;

        }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bola = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bola.gif"))); // NOI18N
        Bola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BolaMouseClicked(evt);
            }
        });
        getContentPane().add(Bola, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BolaMouseClicked
        myTimer.start();

    }//GEN-LAST:event_BolaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dam108t2e509.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dam108t2e509.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dam108t2e509.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dam108t2e509.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dam108t2e509().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bola;
    // End of variables declaration//GEN-END:variables
    Timer myTimer;
    boolean direccion = true;
}
